openapi: 3.0.0
info:
  title: Almacén API
  description: API para administrar un almacén de productos
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /articulos:
    get:
      summary: Obtener todos los artículos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Articulo'
    post:
      summary: Crear un nuevo artículo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticuloInput'
      responses:
        '201':
          description: Creado
        '400':
          description: Petición incorrecta
  /articulos/{id}:
    get:
      summary: Obtener un artículo por ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID del artículo
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Articulo'
        '404':
          description: No encontrado
    put:
      summary: Actualizar un artículo por ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID del artículo
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticuloInput'
      responses:
        '200':
          description: OK
        '404':
          description: No encontrado
    delete:
      summary: Eliminar un artículo por ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID del artículo
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '404':
          description: No encontrado
components:
  schemas:
    Articulo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        descripcion:
          type: string
        cantidad:
          type: integer
          format: int32
        disponible:
          type: integer
          format: int32
    ArticuloInput:
      type: object
      properties:
        nombre:
          type: string
        descripcion:
          type: string
        cantidad:
          type: integer
          format: int32
        disponible:
          type: integer
          format: int32
